name: dev
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_font_icons: ^2.2.7
  http: ^1.3.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.2.2
  intl: ^0.20.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_analytics: ^11.4.5
  firebase_database: ^11.3.5
  email_validator: ^3.0.0
  crypto: ^3.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
  uses-material-design: true
  assets:
   - assets/appicon.png
   - assets/appicon.webp


